server:
  port: 8888

#saml2:
#  rp:
#    signing:
#      cert-location: "classpath:private.key"
#      key-location: "classpath:private.key"

logging:
  level:
    org:
      springframework:
        security:
          saml2: DEBUG
          web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
